spring:
  cloud:
    function:
      definition: upperCase;log;stringSupplier
    stream:
      default:
        group: logging-consumer
      bindings:
        stringSupplier-out-0:
          destination: upperCase.topic
        upperCase-in-0:
          destination: upperCase.topic
        upperCase-out-0:
          destination: log.topic
        log-in-0:
          destination: log.topic
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true