spring:
  cloud:
    function:
      definition: upperCase;log;stringSupplier
    stream:
      bindings:
        stringSupplier-out-0:
          destination: upperCase.topic
        upperCase-in-0:
          destination: upperCase.topic
          group: logging-consumer
        upperCase-out-0:
          destination: log.topic
        log-in-0:
          destination: log.topic
          group: logging-consumer
      rabbit:
        bindings:
          upperCase-in-0:
            consumer:
              auto-bind-dlq: true
          log-in-0:
            consumer:
              auto-bind-dlq: true
